apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bmc-super3-blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    password: AgAjFAjeW5y/V5yLCPS06f8VXAF0zak4O3/o0DMptRbuW61OR99sPbj3ZQ22v5nSJM4NwZbWLZAcGOo2uQhjEaV/PDOY9mnMCQ0Ml3rz1zgsXHDSHDDwSdnbC2n7f+HPcLSosbbZNUCr3qT4Cj452tNh6rwk3nVn7S2D8FhYhZJy4tZHtaku2NnVjvfGEqR2+oaol+e1ON/PjlSU7CSzTMMQ3QTaHKBBLDgupU1EMatElac7RdLr0DJrl06IRbWaFbozdMmRO3uf+9HkNOdb8jdWDpHuBdbDxzRoCsawalRCEs07jJGKioFeWm8Gn7D0HNQzRhjixSr5Uw0WNp7kQXQjYwdVFlWll18P4K44F3au5Vc+1cyp9HBf5IBBCBF0Q0sYEfxGvxAuEP/Mj+0pokQSXNNp0dnH4r7d3neZQvaEizyZNJFjSKRcApCOK7Nd/J0t9CepBnbIpBle71VsNBlf4tIv3XnSA6bA9EQRhWTUVLQYxOWHi7U9UNTbzSQIZJUJ2tgBM5MXy9yocH6HNsgkSxngmn7juaJlPcR6ZWfx7YAlyPFP8eCJG8OvFlB5kGIwh8VFjw8o5UJU6rQT0DBAvPcSiX2chZf6i/6vgfLnXh1tCdpQAophDe6Cj8a0AsIpP2IdG7f0NGakyriP5mr1pYeFKmkEN0+PEsOE+u8g6RP1GcLTBoUXgBLUDi45RUSwXwZLJTeT5Yln2vY=
    username: AgAMMbMzcp5FcX8G0ZdvL/ess1ucgDw4HWGSC5iuzA+e7YkUK6yBJQIKVj6ebZBV4o84Eil1N/FXZT5WZH4RdkbS6SMXTJixGPeLdzG5nTsjdyZbHamxDpxrRPptTfEWAnKflmiB8X/y57AlnINM7KyOfnxevvbZuI7ac9u8KTa/b1AWl+Rm+OxyMuKA8UF86svZsFSgSFC/b5jEjq8Fig3x6yyegCHmoD7ZdrQkuULsz8fV4IvdOK50SW02Ybyj4VQI4bd9AYRXJz7Ecygx+XXt1mvo9q6eWDidHJWKFYLRwPWgCycu78/khYCI9q0c2DEOEnUoWFvvORJOgEMsG9BuWKIPw6YF7J5zmeWlheNlBHqc2yS/RzTnowao6Otnq0bdPbS3DDEjA7IHjlO3WiqHm7TKHacRVxc/X7TUQ6aZxShErm1ElP/3jPf0N27j23+654LngCnjxb+TbdTtxXL+P6ozyQ8XVoeJDahTmxOSSFIJHUDbHkVH3kJg/idZEq3X3rmoTgJ0ZAT5cM+3Q3/VkYcCi2K/cMwLiwxS8c3xHpUuVit/DN66m5hDu48UrO/OSXC8qIgHIp0dymO1CTVSBNHpU+oY9woWFmhSTI7vJjVUM6r8+anV444geiiXpkiYwxY/BwczAgncebCRewDzR2RwozQb7S8n5ysFodLoUOvS639d98f29hAxwU7AeV32XepK
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: bmc-super3-blazer-cars-lab
      namespace: blazer-cars-lab
    type: Opaque

