apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bmc-super1-blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    password: AgAO8LmT4d+x7IdmJvsjlrOSmlKAPT9zkhYuj4agJedXXhIT8Og6aqojLdY7nvOrtoWaDqVcGLdkN9FXrfd/+5lGG11WGhEH7JCTNt+Q3qLeZjuRWMeFZMrhIlFS/9ofvVd698+iaK0RcUOwkZ3ays9ZAFRtP3KRAqo/l69iJd/E8wiS3B6FMiNHnYxwJRQA0ml5ogN7k6EXMXcCy4+f8Uhm+UQPd/unp6OMlYvAmPYvvCF2IaXGMEj8PZJvHrGIS2KuArDOyHag7RKWYJQsJaPiZ/UXGFj3zB2/x+yQmgX2OWhDXNc56g3KL80F3P8xKRJmkNW1yAAArbQpfAed4Vw4KhrN3/CAgTiuOCUOurRCkMlFFbISgexMmO9MVHzyacAGXxF2Lqm+DtshHVL6HuwD9lioA7XiGMB/PIQCOxRPUSlRfD57IMO3OY00OOFotr8avgMus0LKVf8ZLRMC4yxXyBYuTSMcGyZFuFSX7SHrFRBqGSOB61vwA1pnU5safZyzjX5EV8FRaBPdnqn+gQCQKZD/cJaZUVZBN82zBOf76YsDqokbyIdlz4RloAp0yIPJIqzAdvEv3r5YOiYSqDV3QL8wZuT9ixwhGivuIPzFxUrlC5oA4MuCTJbeGCrghqmV8sCK4MeUaYhqDaNYXFZX2w05RAKrnBzof0wHpKZSN3B5AmsCvtrY6LLqnuOHFgzNTuiFuyg+fmTyRt8=
    username: AgBAIMGjC8CByudU0+MMeTvtLm66sJmlD6q1QyLRj523WYuzDCTgDdPqdgU7w6/rGgHMAndp68eXNa9nDFmOU7sRuzAX2zMjUkrH9nK3atJ0ebZ9eZfe3QpB9Vqcd+SoPtkMK1B+jght6mw4m7DzUy+ulYwJN84Z0XL0alFTxBtCOpKNaHmq4kk/TaXd/iRufMis8OnAFg4ZNn4LZuS602LBHqMfgKaNHL/RgEtA8HsDvcio9JgX/0Fno0QNWfisn1hK90lodiCI6cHDSLYTjxU2OQETtRKKwUXbc49CqkqOL9QHVVokiYIdmwWfAHLbEEQw1Bc9C3PHjcMmRhnLmSM9hirRF76LVtTGYk5yT5+3CvAllWHarcFeCz5ZV4euikDoiQ7O9IwTHjncXEd/bU49OM1bn5SR6ksHOcWOj7s4S/V3xcxtisq6m67JJ2u2qUncdWNpCUhDQMfzeSrWERVmeQaYkTyQ6ZL5mnZs4Awz5J+yvRM36TnFXq1pUVF03Y4U18L0ga0RJnQi/MGedjHYEtwXc5Zdn1p8dG3f4wxDUF9tfK5MiVZJhgQ20JjDAMUPLqSmKNFclviAehErazfcvIl0bC+D6rQ4tSDOK/Riy/2w/RYu6rWVBVk1PPELXAHDeAmhMJh5Ex9z6a0JdygmjS+l7JmCIciHaVCHAiBUK9TvLmb2vtIRQ9iY5qZIWJ5/fxrO
  template:
    data: null
    metadata:
      annotations:
        argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
        argocd.argoproj.io/sync-wave: "1"
      creationTimestamp: null
      name: bmc-super1-blazer-cars-lab
      namespace: blazer-cars-lab
    type: Opaque

