apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: bmc-super3-blazer-cars-lab
  namespace: blazer-cars-lab
spec:
  encryptedData:
    password: AgCTw8HSEOy1cjvg3AZ4o+jabfhMgD7xK9g6qe2ANKemcjqJ87hxikbyQLZVx9z0SxBM1Ke54TG9vNXyEx3uhTehuo3hheM75YSQ4/PwjCmTTM/YfSIsP2LFB81Jzk9eswWyVeAqWWSNMoahqversFGg4o0ay9JGtD6YNaMOiecOWouCVMt276sq+3mRmOoXL38a8V/52FIFbgqe/56kk49hV3qZErmJqoamdsJdYbnLSw6cudUCph3GeqTyAa5ZI9miZXmzY5G700qn3GE2NbTAPfPT0LLmnK0P5ZkI+DYHgSTSBdSssf9vCIjh7K7MM8Bhhcva5y8W1MANbuLIGGYmebHd1n/75HePHhNFo8Rn/hyjGHYqKEA8v2X5jO/Sp/7GjaDyBl/iww0g1Li0QBpPe94CIMyKTsLV0vPEVfYgf3Be70VozujtLNYARAk3lDIGDZhCb7Xnb/gE3CIC8EiHlplFW/YMwL68ZVyZ1V7W1IaYSjbqVqDsOwWu0n0vCImByEgrBS4LrPG0plaCJHsSv8AbFQUXcP30I2/V8zfkIr9zoNZQka6SbE/gRIqk8yOesxkfeyD543TF7an//mVgZwNzue9BiXntjf9Ugy/kB5Nwy0ORUU+KGmVcyiOVvCCjulcq0QeRCBIG4xUhe7NzsiHSkm19RcP2+FgRcDkrLk8XL70q307d5PjPTeAAf9F4t/BzA0+vaVeA608=
    username: AgCEmxexuA1DHl//83/dSICVzna6SG2EZHE5J+sherUITBz/Ww3l3kmDDVzX9xBva/17CwgkyRP1FtNahBKvBTC/tjOiBfFqGnAXnQKA5nj8xdF+72IEXsGl3TZTHZaR9z3bE5hYK/3CnBErCJi4iO1zagcqOA2GNBCXXFL93CUEbc0J3zT5aRrDon9rHCyep4Os/Odlf/sfqRgu/MNdSvyRljmfVAau2CINrZMsnjLysGErKTswsPB058ZxXcHNADz4EETz6HrMtfC+0v0Wd2yeQqBO40ceokFpgvB5mEr2IT9123REiYOA0N71GBQmfeGXCY6b5nm02P1hdVolFgGcm39tvWi1LQY1NSNfnko/T+YfBahwBajI9pKgNWTcSq9ajWpFZYCfoe/o09qtSO6q4syKZJWR3T+JJpccLSeR1C6URujx3nSNl9kNVknJo/Ya7ucnYt8/QJjMMF/ATy7W4dX3d3Kezr0lOcrl7XtXLPUXxvFJPG6SCJbIsfCgLAQQhlHc4MYPqD7QhPEkhK9FCZwfHMwMlR+eCMU3+K/Pewc3/scp5MPLOU0omLLm50LAiGEsmIGD1IwjmHS5XwjNCxlYD/yse0ofXtIAueN4VCmwMnyhn8gm3CTKJwCHEorEANuZ9wNyuE1MwHBkMQDGIlac984mJpmBpOU3/qsR28u+ZovRxsBKGdss0LNbWWW0z+Ty
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: bmc-super3-blazer-cars-lab
      namespace: blazer-cars-lab
    type: Opaque

