---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: blazer-cars-lab
  namespace: blazer-cars-lab
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "4"
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
