apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/natifridman/openshift-gitops-kustomize
      revision: main
      directories:
      - path: cluster-mgmt/test/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/natifridman/openshift-gitops-kustomize
        targetRevision: main
        path: '{{path}}'
        plugin:
          name: argocd-vault-plugin-kustomize
      destination:
        server: https://kubernetes.default.svc