apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openshift-wildcard
  namespace: openshift-ingress
spec:
  secretName: openshift-wildcard-certificate
  issuerRef:
    name: cert-manager-webhook-dnsimple-production
    kind: ClusterIssuer
  commonName: '*.apps.ipi-bm-demo02.clustership.com'
  dnsNames:
  - '*.apps.ipi-bm-demo02.clustership.com'
