apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases: 
- github.com/redhat-cop/gitops-catalog/cert-manager-operator/operator/base?ref=main

# patchesStrategicMerge:
# - subscription-admin-patch.yaml

#patches:
#- path: subscription-admin-patch.json
#  target:
#    group: rbac.authorization.k8s.io
#    version: v1
#    kind: ClusterRoleBinding
#    name: open-cluster-management:subscription-admin
